name: PanaGeoBot Update
on:
  schedule:
    - cron: '0 9 * * 3'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Engine
        env:
          PG_PI_X: ${{ secrets.PG_PI_X }}
          PG_PI7: ${{ secrets.PG_PI7 }}
          PG_PPI5: ${{ secrets.PG_PPI5 }}
          PG_PI2: ${{ secrets.PG_PI2 }}
          PG_PI0: ${{ secrets.PG_PI0 }}
          PG_MD: ${{ secrets.PG_MD }}
        run: python UFL/generate_projections.py

      - name: Sync Main
        run: |
          git config --global user.name "PanaGeoBot"
          git add UFL/panageo.htm
          git commit -m "UFL Sync"
          git push origin main
